export const PRODUCTS = [
  {
    name: "물",
    username: "총명한 판다",
    description: "깨끗하고 맛있는 물입니다.",
    price: 5000,
    tags: ["음식", "생활용품"],
    images: [],
    likeCount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "컴퓨터",
    username: "총명한 판다",
    description: "최신형 컴퓨터입니다.",
    price: 500000,
    tags: ["전자기기", "컴퓨터"],
    images: [],
    likeCount: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "책",
    username: "총명한 판다",
    description: "베스트셀러이고 한 번만 읽은 책입니다.",
    price: 10000,
    tags: ["도서", "취미"],
    images: [],
    likeCount: 94,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "화장품",
    username: "총명한 판다",
    description: "미개봉 색조 화장품입니다.",
    price: 6000,
    tags: ["미용"],
    images: [],
    likeCount: 24,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "달력",
    username: "총명한 판다",
    description: "2025년 은행 달력입니다.",
    price: 5000,
    tags: ["사무용품", "문구", "새해"],
    images: [],
    likeCount: 77,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "화장지",
    username: "총명한 판다",
    description: "잘풀리는 집 화장지입니다.",
    price: 2000,
    tags: ["생활용품", "화장지"],
    images: [],
    likeCount: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "거울",
    username: "총명한 판다",
    description: "한쪽은 3배 크게 볼 수 있는 거울입니다.",
    price: 3000,
    tags: ["미용", "생활용품"],
    images: [],
    likeCount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "마우스",
    username: "총명한 판다",
    description: "최신형 미개봉 마우스입니다.",
    price: 30000,
    tags: ["전자기기", "컴퓨터"],
    images: [],
    likeCount: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "베개",
    username: "총명한 판다",
    description: "한 번만 쓴 경추베개입니다.",
    price: 20000,
    tags: ["침구", "생활용품"],
    images: [],
    likeCount: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "파우치",
    username: "총명한 판다",
    description: "화장품이나 생활용품을 담을 수 있는 파우치입니다.",
    price: 4000,
    tags: ["미용", "생활용품"],
    images: [],
    likeCount: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "슬리퍼",
    username: "총명한 판다",
    description: "실내용 슬리퍼입니다.",
    price: 10000,
    tags: ["생활용품", "신발"],
    images: [],
    likeCount: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "스피커",
    username: "총명한 판다",
    description: "블루투스 스피커입니다.",
    price: 600000,
    tags: ["전자기기", "음향"],
    images: [],
    likeCount: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "커텐",
    username: "총명한 판다",
    description: "공부할 때 좋은 암막 커텐입니다.",
    price: 70000,
    tags: ["인테리어", "생활용품"],
    images: [],
    likeCount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "카페트",
    username: "총명한 판다",
    description: "집 분위기를 바꿔주는 카페트입니다.",
    price: 40000,
    tags: ["인테리어", "생활용품"],
    images: [],
    likeCount: 31,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "선풍기",
    username: "총명한 판다",
    description: "지난 여름에 새로 샀던 선풍기입니다.",
    price: 10000,
    tags: ["전자기기", "여름"],
    images: [],
    likeCount: 54,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "협탁",
    username: "총명한 판다",
    description: "침대 옆에 두고 쓰는 협탁입니다.",
    price: 200000,
    tags: ["인테리어", "수납"],
    images: [],
    likeCount: 53,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "가방",
    username: "총명한 판다",
    description: "두 번만 쓴 백팩 가방입니다.",
    price: 5000,
    tags: ["패션", "백팩"],
    images: [],
    likeCount: 67,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "필통",
    username: "총명한 판다",
    description: "새로 사고 한 번도 안쓴 필통입니다.",
    price: 5000,
    tags: ["문구", "새학기"],
    images: [],
    likeCount: 43,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "세탁기",
    username: "총명한 판다",
    description: "21년형 드럼 세탁기입니다.",
    price: 300000,
    tags: ["가전제품", "이사"],
    images: [],
    likeCount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "조끼",
    username: "총명한 판다",
    description: "겨울에 따뜻하게 입을 수 있는 조끼입니다.",
    price: 30000,
    tags: ["패션", "겨울"],
    images: [],
    likeCount: 24,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "의자",
    username: "총명한 판다",
    description: "허리를 보호해주는 책상용 의자입니다.",
    price: 20000,
    tags: ["인테리어", "생활용품"],
    images: [],
    likeCount: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "퍼즐",
    username: "총명한 판다",
    description: "심심할 때 즐겁게 할 수 있는 퍼즐입니다.",
    price: 4000,
    tags: ["취미", "퍼즐"],
    images: [],
    likeCount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "매트리스",
    username: "총명한 판다",
    description: "꿀잠 잘 수 있는 매트리스입니다.",
    price: 100000,
    tags: ["침구", "인테리어"],
    images: [],
    likeCount: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "TV",
    username: "총명한 판다",
    description: "최신형 스마트 TV입니다.",
    price: 500000,
    tags: ["전자기기", "가전제품"],
    images: [],
    likeCount: 58,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const ARTICLES = [
  {
    username: "총명한 판다",
    title: "안녕하세요~",
    content: "반갑습니당!",
    images: [],
    likeCount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "컴퓨터 중고 삽니다.",
    content: "일반 사무용으로 사고 싶습니다. 연락 주세요",
    images: [],
    likeCount: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "판다마켓 좋네요!",
    content: "앞으로 자주 이용하겠습니다^^",
    images: [],
    likeCount: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "중랑구 사시는 분 있으신가요",
    content: "제가 곧 이사를 가는데 책상을 사고 싶습니다. 파실 분 연락 주세요.",
    images: [],
    likeCount: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "판다마켓에서 원하는 물건 찾으려면 어떻게 하는지 아시는분",
    content: "제곧내",
    images: [],
    likeCount: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "여의도에 사시는 분들은 아이폰 거래 시 조심하세요.",
    content:
      "이번에 아이폰 중고로 사신다고 해서 만났는데 사기 당할 뻔 했네요;; 여러분도 조심하세요.",
    images: [],
    likeCount: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "안녕하세요~ 이번에 가입했습니다.",
    content: "저는 대전에 살고 있습니다. 대전 유저분들 친하게 지내요!",
    images: [],
    likeCount: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "안녕하세요 묵동 외톨이 인사박습니다.",
    content:
      "저는 34년을 외롭게 지냈습니다. 이 글도 댓글이 없어서 혼자 울며 자겠지요..",
    images: [],
    likeCount: 10000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    username: "총명한 판다",
    title: "2030 러닝 크루 모집(남자마감)",
    content:
      "2030 달산(달려야 산다) 모집합니다. 현재 여자 10명, 남자 20명으로 여자 10명 충원중입니다..",
    images: [],
    likeCount: 35,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const COMMENTS = [
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 2,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 8,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 9,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 2,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 8,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 9,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 2,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 8,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 9,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 1,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 2,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 4,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 5,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 8,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    articleId: 9,
    username: "똑똑한 판다",
    content: "좋은 글 잘 읽었습니다.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
